### ISSUE TITLE
Zbattle not fully working.

### ISSUE THREAD

**Issue by asasnsba** [daye10/dokkan-battle-farm-bot-app#2]
With the zbattles command it does some of the z battles but not newer ones. With the zstages command it does not let you do any of the newer ones either (may be with the older ones too havent tried).

**Comment by daye10** [comment]
oh ok... thanks for the feedback, I'll try to fix it asap, it may take a little while, sorry I'm a little busy at this time.

note : if you try to do it from an account you just created, it might not work too, since version Z, you have to finish the story mode with raditz of the tutorial before unlocking the battle z and the potential awakening

there is still a lot of improvement to do for it to be like 16 too, if it the error doesn't come from there I'll keep you informed as soon as it's fixed, ill try to look for it before next week 👍

**Comment by asasnsba** [comment]
Hey, I know you said you would get to fixing this issue when you can but I am writing this as a reminder incase you forgot.

**Comment by daye10** [comment]
yea... I hadn't forgotten, I keep it in a corner of my mind, unfortunately I still haven't found the time to focus on it, thanks for the reminder, don't worry I'll work on it asap !

**Comment by daye10** [comment]
finally done :)
